# coding: utf-8

"""
    Kingpick Image ingestion jobs API

    Image ingestion jobs.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cvtool_jobs_client
from cvtool_jobs_client.rest import ApiException
from cvtool_jobs_client.apis.job_api import JobApi


class TestJobApi(unittest.TestCase):
    """ JobApi unit test stubs """

    def setUp(self):
        self.api = cvtool_jobs_client.apis.job_api.JobApi()

    def tearDown(self):
        pass

    def test_add_step(self):
        """
        Test case for add_step

        
        """
        pass

    def test_create(self):
        """
        Test case for create

        
        """
        pass

    def test_end_job(self):
        """
        Test case for end_job

        
        """
        pass

    def test_get(self):
        """
        Test case for get

        
        """
        pass

    def test_start_job(self):
        """
        Test case for start_job

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
