# coding: utf-8

"""
    Kingpick Image ingestion jobs API

    Image ingestion jobs.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NewJobRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type=None, auto_start=False, input_params=None):
        """
        NewJobRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'type': 'str',
            'auto_start': 'bool',
            'input_params': 'JobInputParameters'
        }

        self.attribute_map = {
            'type': 'type',
            'auto_start': 'auto_start',
            'input_params': 'input_params'
        }

        self._type = type
        self._auto_start = auto_start
        self._input_params = input_params

    @property
    def type(self):
        """
        Gets the type of this NewJobRequest.
        Job type

        :return: The type of this NewJobRequest.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this NewJobRequest.
        Job type

        :param type: The type of this NewJobRequest.
        :type: str
        """
        allowed_values = ["csv", "flickr"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def auto_start(self):
        """
        Gets the auto_start of this NewJobRequest.
        create job and start ?

        :return: The auto_start of this NewJobRequest.
        :rtype: bool
        """
        return self._auto_start

    @auto_start.setter
    def auto_start(self, auto_start):
        """
        Sets the auto_start of this NewJobRequest.
        create job and start ?

        :param auto_start: The auto_start of this NewJobRequest.
        :type: bool
        """

        self._auto_start = auto_start

    @property
    def input_params(self):
        """
        Gets the input_params of this NewJobRequest.

        :return: The input_params of this NewJobRequest.
        :rtype: JobInputParameters
        """
        return self._input_params

    @input_params.setter
    def input_params(self, input_params):
        """
        Sets the input_params of this NewJobRequest.

        :param input_params: The input_params of this NewJobRequest.
        :type: JobInputParameters
        """

        self._input_params = input_params

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NewJobRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
